### ISSUE TITLE
Reports backend implementation

### ISSUE THREAD

**Issue by ACHultman** [SENG426-Summer-2022/vega-spring-master#3]
**Feature description**
This issue includes the API endpoints, db queries, and business logic required to serve the weekly secret entry reports to the report page.

**Proposed solution**
This implementation will be added to the Java Spring implementation similar to the adminpanel route.

**Describe alternatives you've considered**
None.

**Additional context**
This ticket is part of the admin simple report feature.

**Story points**
8

**Comment by Gavinok** [comment]
replaced with user crud
