### ISSUE TITLE
User sign up missing

### ISSUE THREAD

**Issue by bmazerolle** [SENG426-Summer-2022/vega-spring-master#4]
**Feature description**
The front end is missing sign up UI and the backend already has this functionality in the LoginController, so we need to hook the two together.

**Proposed solution**
Hook into the /register endpoint from the front end

**Describe alternatives you've considered**
N/A

**Additional context**
Existing code: https://github.com/SENG426-Summer-2022/vega-spring-master/blob/master/src/main/java/com/uvic/venus/controller/LoginController.java#L82

**Story points**
8

**Comment by Gavinok** [comment]
@bmazerolle This was actually already covered
